config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :articles
  resources :trips do
    collection do
      get 'trip_museum_delete'
      get 'trip_museum_toggle'
      get 'trip_delete'
      get 'museums'
    end
  end

  # Defines the root path route ("/")
  root 'users#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/museum.rb
class Museum < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
end

app/models/trip_museum.rb
class TripMuseum < ApplicationRecord
  belongs_to :trip
  belongs_to :museum
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :authenticate

  def index
    @trips = Trip.where({
      'user_id': @user.id,
      'multi_city': params['multi'] == "1" ? 1 : 0,
      })
  end
  def new
    @museums = Museum.all()
  end
  def create
    params.permit!
    pt = params['trip']
    if !pt || !pt['name'] || pt['name']=='' || !pt['date'] || pt['date']==''
      return report_error('you should specify the name and the date of the trip')
    end
    pm = params['museum']
    if !pm || pm.keys.size == 0
      return report_error("a trip should have at least one museum")
    end
    @trip = Trip.new(pt)
    @trip.user_id = @user.id
    n = Time.now.strftime("%Y-%m-%d")
    regex = /\d{4}-\d{2}-\d{2}/
    if @trip.date !~ regex || @trip.date <= n
      return report_error('bad date, should be a future date formated like "2001-05-15"')
    end

    ks = pm.keys
    cities = Museum.where(id: ks).select('city').uniq
    @trip.multi_city = cities.size >= 2 ? 1 : 0

    @trip.save
    ks.each do |m|
      tm = TripMuseum.new({'trip_id':@trip.id, 'museum_id': m})
      tm.save
    end
    redirect_to '/trips'
  end
  def show
    @trip = Trip.find(params[:id])
    ms = TripMuseum.where({'trip_id': params['id']}).select('museum_id')
    @museums = Museum.where({'id': ms})
  end

  def museums
    mids = Hash.new
    TripMuseum.where({'trip_id': params['id']}).each do |k|
      mids[k.museum_id] = 1
    end
    @trip = Trip.find(params[:id])
    @museums = Array.new
    Museum.all.each do |museum|
      @museums << {
        "name": museum.name,
        "city": museum.city,
        "state": museum.state,
        "description": museum.description,
        "id": museum.id,
        "selected": mids[museum.id]==1,
      }
    end
  end
  def trip_museum_delete
    TripMuseum.where({'trip_id': params['tid'], 'museum_id': params['mid']}).destroy_all
    redirect_to '/trips/'+params['tid']
  end
  def trip_museum_toggle
    if params['op'] == 'del'
      TripMuseum.where({'trip_id': params['tid'], 'museum_id': params['mid']}).destroy_all
      update_multi(params['tid'])
    else
      TripMuseum.new({'trip_id': params['tid'], 'museum_id': params['mid']}).save
      update_multi(params['tid'])
    end
    redirect_to '/trips/museums?id='+params['tid']
  end
  def trip_delete
    TripMuseum.where({'trip_id': params['id']}).destroy_all
    Trip.find_by_id(params['id']).destroy
    redirect_to trips_path
  end

  private
  def report_error(msg)
    redirect_to '/trips/new', alert: msg
  end
  def update_multi(tid)
    ids = TripMuseum.where({'trip_id': tid}).select('museum_id')
    cities = Museum.where(id: ids).select('city').uniq
    trip = Trip.find_by_id(tid)
    trip.multi_city = cities.size >= 2 ? 1 : 0
    trip.save
  end
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      user = User.find_by_email(username)
      if user && user.password == password
        @user = user
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
  def create
    @user = User.new(user_params)

    @user.save
    redirect_to '/trips'
  end

  private
    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trips/index.html.erb
<a href="/trips/new">New Trip</a>
<style type="text/css">
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
</style>

<div> <span><%= link_to 'DayTrip', '/trips' %></span>&nbsp; &nbsp;<span><%= link_to 'MutipleDayTrip', '/trips?multi=1' %></span></div>
<table>
  <tr>
    <th>name</th>
    <th>date</th>
    <th>type</th>
    <th colspan="2"></th>
  </tr>

  <% @trips.each do |trip| %>
    <tr>
      <td><%= trip.name %></td>
      <td><%= trip.date %></td>
      <td><%= trip.multi_city == 1 ? 'Multiple Day Trip' : 'Day Trip' %>
      <td><%= link_to 'Show', trip_path(trip) %></td>
    </tr>
  <% end %>
</table>

app/views/trips/museums.html.erb
<%= link_to 'Back to Trip', trip_path(@trip) %>
<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>OP</th>
  </tr>

  <% @museums.each do |museum| %>
    <tr>
      <td><%= museum[:name] %></td>
      <td><%= museum[:city] %></td>
      <td><%= museum[:state] %></td>
      <td>
      <% if museum[:selected] %>
        <%= link_to 'Delete', '/trips/trip_museum_toggle?op=del&mid='+museum[:id].to_s+'&tid='+@trip.id.to_s %>
      <% else %>
        <%= link_to 'Add', '/trips/trip_museum_toggle?op=add&mid='+museum[:id].to_s+'&tid='+@trip.id.to_s %>
      <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/trips/new.html.erb
<% flash.each do |type, msg| %>
  <div style="color:red">
    Error:
    <%= msg %>
  </div>
<% end %>

<p>
  Current User: <%= @user.email %>
</p>
<%= form_for :trip, url: trips_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.submit %>
  </p>
  <% @museums.each do |museum| %>
    <p>
      <%= check_box_tag("museum["+museum.id.to_s+"]") %>
      <%= museum.name %>
    </p>
  <% end %>
<% end %>

app/views/trips/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @trip.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @trip.date %>
</p>

<p>
  <strong>Type:</strong>
  <%= @trip.multi_city == 1 ? 'Multiple Day Trip' : 'Day Trip' %>
</p>

<p>
<%= link_to 'Delete', '/trips/trip_delete?id='+@trip.id.to_s %>
</p>

<p>
<%= link_to 'Add Museum', '/trips/museums?id='+@trip.id.to_s %>
</p>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th>OP</th>
  </tr>

  <% @museums.each do |museum| %>
    <tr>
      <td><%= museum.name %></td>
      <td><%= museum.city %></td>
      <td><%= museum.state %></td>
      <td><%= link_to 'Delete', '/trips/trip_museum_delete?mid='+museum.id.to_s+'&tid='+@trip.id.to_s %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<p>
If you don't hava a user, you can register one, and then go to the trips list.
</p>
<p>
Or you can go to the <a href="/trips">trips page</a> directly
</p>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label 'Email' %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label 'Password' %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit 'Register' %>
  </p>
<% end %>